### ISSUE TITLE
Feature request: Please allow pausing list updates!

### ISSUE THREAD

**Issue by nylen** [htop-dev/htop#103]
When sorting by CPU usage it would be very useful to be able to pause the updates temporarily, but still be able to scroll around in the list and take other actions (see the command line for a process that is taking up a lot of CPU, kill it, etc).

An alternative would be to keep the list updating normally but temporarily freeze the _sort order_ of the list. Either one of these features would make it much easier to inspect and modify a process that is using a lot of CPU or other resources. Currently this is difficult because the processes usually move around while you are trying to inspect them.

Links to previous discussion:

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821904
- https://superuser.com/questions/1036978/how-to-freeze-the-list-of-processes-in-htop
- https://unix.stackexchange.com/questions/292902/is-it-possible-to-freeze-task-order-in-htop

**Comment by duchampdev** [comment]
If wanted, I could have a look at how to implement this as I would appreciate such a feature as well.

**Comment by fasterit** [comment]
From IRC when another user asked similarly:
&lt;DLange&gt; I'm sure a good implementation of #103 will be well received. It's not trivial though.
&lt;DLange&gt; Talk to @cgzones who had an idea on how to separate the update from the drawing logic so that the former can be suspended / resumed at will.
&lt;DLange&gt; And notice people will immediately ask for sort changes / tree on, off etc. with their non-updating data :)

**Comment by eworm-de** [comment]
Looks like #214 addresses this.

**Comment by cgzones** [comment]
Should be closed by #204; feel free to reopen or open a new issue if some functionality is missing.

**Comment by BenBE** [comment]
> Should be closed by #204; feel free to reopen or open a new issue if some functionality is missing.

You mean #214 I guess. #204 does something completely different … ;-)
