### ISSUE TITLE
Feature request: Account for zswap in memory usage

### ISSUE THREAD

**Issue by SharkWipf** [htop-dev/htop#104]
This may be out of scope for htop, but currently htop has no way of accounting for zswap usage.
Unlike zram, zswap does not create a virtual, dynamically resizing swap device, nor does it report the compressed size to the OS through the normal channels.  
Instead, it reports the _uncompressed_ size to the OS, and keeps the real stats to itself in `/sys/kernel/debug/zswap/`.
As a result, the uncompressed swap usage can exceed the real swap device size, the OS will report the actual swap device as full (despite it possibly not being touched by swap at all), but will continue filling up zswap in the background with no way to see it in `htop` (or `free`, for that matter):

![image](https://user-images.githubusercontent.com/751205/92417780-44b5a500-f164-11ea-9de5-a9c71d7f4538.png)

It would be more accurate, albeit potentially out of scope, to account for zswap usage in the swap usage, showing the compressed swap rather than the uncompressed swap.

**Comment by Skirmisher** [comment]
It's unfortunate that there's no way to access zswap statistics without requiring users to have debugfs mounted and readable without root. IMO, even if swap usage is not corrected, a zswap meter (similar to the zram one) would be most immediately useful for assessing the status of system memory/swap on a zswap-enabled system. Perhaps implementing such a thing would make sense even with the extra setup requirement, for the benefit of those who require it. (I'm moving my Fedora system over to zswap from zram, since I have a large swap partition that's being suboptimally used due to zram being full, and came here while looking for a replacement solution for htop's zram meter.)
