### ISSUE TITLE
assertion in Vector_checkArraySize fails when setting the core affinity

### ISSUE THREAD

**Issue by lbckmnn** [htop-dev/htop#1188]
The function  `Vector_checkArraySize` seems to be originally designed to be called when the vector is full (hence the `assert(Vector_isConsistent())`). This works fine, when `Vector_checkArraySize` is called every time **after** adding (exactly one) element. This is the case in `Vector_set`

https://github.com/htop-dev/htop/blob/e3481a9846ef01bb27c169b71eafeee704e10c68/Vector.c#L203-L214

However, the function `Vector_splice`uses this function to reallocate for (possibly) more than one element. 

https://github.com/htop-dev/htop/blob/e3481a9846ef01bb27c169b71eafeee704e10c68/Vector.c#L396-L406

When the new size is larger than the current array size, the assertion `Vector_isConsistent` in `Vector_checkArraySize` fails.

This can be triggered by pressing `a` (setting the core affinity)  in a debug build of htop because `Vector_splice` is called then. 
However, the assertion does probably only trigger on machines with more than 10 cores (this is the default vector size).

**Comment by BenBE** [comment]
The assert failing is a symptom, not the root cause. The consistency checks are there for a reason.

Looking at the code it looks more like `Vector_splice` is misusing the `Vector_checkArraySize` function.

I think a better change, which also better encapsulates what the intention is, would be to have `Vector_checkArraySize` be renamed to `Vector_checkArrayResize` and provide the new size for it, thus ensuring the consistency before, performing the resize and ensuring consistency after the resize. With the current PR you run the risk of some caller not properly checking consistency of the vector before the resize is performed.

**Comment by lbckmnn** [comment]
Yes that is probably a good idea, i will update the PR.

**Comment by lbckmnn** [comment]
While implementing the changes i noticed that `Vector_set` and `Vector_insert` are somewhat inconsistent when it comes to dealing with indices greater than the current length. Both seem to support adding elements in a different way.

`Vector_insert`: When called with e.g. index 15  and `this->items == 10`, the element is just inserted at the end.
https://github.com/htop-dev/htop/blob/e3481a9846ef01bb27c169b71eafeee704e10c68/Vector.c#L222-L224

`Vector_set`: When called with index 15 and `this->items == 10`, index 15 is written, leaving the elements in between uninitialized. When called with indices > this->arraySize we have a heap overflow. 
https://github.com/htop-dev/htop/blob/e3481a9846ef01bb27c169b71eafeee704e10c68/Vector.c#L343-L345

Both are not ideal in my opinion.
How should I deal with this?
I think the following behavior would be good:

`Vector_set` is not allowed to alter the size at all (can be asserted).

`Vector_insert` inserts one element which can be at the end, but not for example at index 15 when the current size is 10 (can also be asserted). 

However, the places in which `Vector_insert`  and `Vector_set` are called might also need adjustments.

**Comment by cgzones** [comment]
@BenBE what was the reason for https://github.com/htop-dev/htop/commit/a94fd87b05aa23d453d6e238746b5a55e75544bd? (performance?)
Because it changed the condition for owned vectors in `Vector_isConsistent()` from
   *all slots that contain an entry must be of the expected type*
to
  *all slots must contain entries*.

**Comment by lbckmnn** [comment]
@cgzones #315 was the respective PR. 
The reason was the quadratic runtime complexity.

**Comment by cgzones** [comment]
> @cgzones #315 was the respective PR. The reason was the quadratic runtime complexity.

Thx.

TODO list:
* The wrong owner condition in `Vector_isConsistent()` should be dropped.
* `Vector_set()` should assure the vector is resized if idx is bigger than current capacity.
* Multiple functions should ensure slots not containing entries should be set to `NULL`: `Vector_checkArraySize()`, `Vector_take()` and `Vector_compact()`.

**Comment by lbckmnn** [comment]
Then `Vector_insert()` should still insert at the end, when `vector_insert()` is called with an index way past the current number elements? That might be very unexpected.

**Comment by cgzones** [comment]
Is it? In C++ and Rust using insert past the last element is not supported at all. Since we don't expect the call to fail reducing the index in that case seems reasonable.

**Comment by lbckmnn** [comment]
Wouldn't you want an assertion to be triggered if you inserted past the end? 
If i insert an element at index 15, I expect the element to be at index 15 if, I don't call any operation that invalidates that index.

**Comment by BenBE** [comment]
I could live with this additional constraint on `Vector_insert`, if the changes needed to existing source are minimal, i.e. this does not require any structural changes because this does not introduce an additional constraint that was not met before anyway.

But in a first step, we should not aim to have this inserted; I think that's a secondary target.

**Comment by lbckmnn** [comment]
Another small thing:
The ownership condition in Vector_splice seems wrong / insufficient. 
https://github.com/htop-dev/htop/blob/89872e33d80f953e8895e0d0d91d8da8b7562438/Vector.c#L396-L401

If `this` is owning its entries and `from` is not, the spliced items are destroyed twice. 

What combinations of owning and non owning vectors should be possible here anyway?
