### ISSUE TITLE
Can't change the last column

### ISSUE THREAD

**Issue by kuraga** [htop-dev/htop#1199]
Good day!

On `Setup -> Screens`, in any of Screen, in `Active Columns` section, I can't change the last.
All my actions (`<F7>`, `<F8>`) changes every column but the last.

htop 3.2.1, Calculate Linux 23 (Gentoo-based).

Thanks!

**Comment by tanriol** [comment]
AFAIK, there's a technical limitation that the command field can only be the last one. A special case related, I think, to really long paths and tree mode using that column for tree-like structure.

**Comment by kuraga** [comment]
@tanriol The same for `IO_WRITE_WRITE` (and `PID`, `USER`, etc. as the neighbors) column in  `IO`

**Comment by systemdarena** [comment]
I manually changed it in htoprc (i added EXE and made it the last column for the I/O tab) and it seems to be working fine. For the Command column of Main tab it makes sense to lock it as last column since it has very long variable length, but for the I/O tab I don't see why IO_WRITE_RATE would be locked in as the last column.

I also did try moving Command for Main tab, just for fun, in my htoprc and it mostly works. The only thing is it doesn't line up everything after it properly into columns, just appends them to the end of each line's command string.

**Comment by fasterit** [comment]
What is the issue here? Command (EXE) shall be last and the `htop` setup screen ensures that.
Works as designed, not?

Of course you can hack your `htoprc` all you want to, you may just keep the pieces then :-).

**Comment by systemdarena** [comment]
Yes, i guess it is working by design right now. I was talking about the I/O tab though, which by design has IO_WRITE_RATE forced to be the last column.

Command and EXE are different columns. It looks like "Command" is not available for the I/O tab, only EXE, which displays only the process name without path or args.

My point is that there seems to be no reason to lock IO_WRITE_RATE as the last column of the I/O tab like there is for Command in the Main tab

**Comment by fasterit** [comment]
The last column in the I/O tab should be "Command" as well.
Can you move your `htoprc` out of the way so `htop` generates a new one? That should fix it?!?

**Comment by systemdarena** [comment]
Hmmm, you are right, Command is now the last column of the I/O tab too. I'm not sure what happened there, but as @kuraga indicated above also, some how IO_WRITE_RATE ended up as the last column for me.

**Comment by hishamhm** [comment]
@fasterit I just logged into an AWS Amazon Linux instance, ran `yum install htop`, it installed htop 3.2.1 and the Command column does not show up in the `I/O` tab, with no way to add it from the UI. I tried deleting ~/.config/htop/htoprc and I get the same behavior. 

Adding it back manually editing htoprc did add Command in the I/O tab.

Like @kuraga, I also did try using the function keys on the `Command` entry (to see if removing it from the Main screen and adding it to I/O would work, as in, "is it allowing just one Command instance globally?"). To avoid such confusion, ideally when selecting the `Command` entry in `Active Columns`, the `F7`, `F8` and `F9` entries should go blank — that will provide enough indication to the user that is immovable.

If I try creating a new tab in `Screens`, it does create a new screen with `Command` as the last, immovable item as expected.
