### ISSUE TITLE
htop tip shows "0 running" processes in the task counter header 

### ISSUE THREAD

**Issue by fasterit** [htop-dev/htop#1256]
Tasks: 151, 1497 thr, 329 kthr; **0 running**
... regardless of how many processes are in **R** state

**Comment by BenBE** [comment]
Looking into this with `git bisect` I found, this was introduced some time after 3.2.2, most likely in commit 72235d8e098d9d79029dca65122605741e1aafad from @natoscott in PR #1234.

**Comment by natoscott** [comment]
@BenBE good catch!  yes, I think its very likely this is a linux-specific issue as a result of the running task accounting happening in 'machine' code instead of 'processlist' code on that platform (opposite to everything else, and that zeroing line you mention now being in a slightly different location).

I'll keep digging into it & should have a fix soon.
