### ISSUE TITLE
Does not show processors for AMD EPYC 9654

### ISSUE THREAD

**Issue by ikey-ru** [htop-dev/htop#1261]
<img width="1114" alt="1" src="https://github.com/htop-dev/htop/assets/47115676/17277431-cde5-4184-80fe-a12fd055c83f">
Do not understand why.

**Comment by natoscott** [comment]
Can you add your htoprc and /proc/stat file contents to the issue?  Thanks

**Comment by ikey-ru** [comment]
[htop.zip](https://github.com/htop-dev/htop/files/11783185/htop.zip)

**Comment by natoscott** [comment]
Looks like you have a relatively large number of CPUs (384) which triggers this logic in Settings.c...

```
   if (initialCpuCount > 128) {
      // Just show the average, ricers need to config for impressive screenshots
      this->hColumns[0].names[0] = xStrdup("CPU");
      this->hColumns[0].modes[0] = BAR_METERMODE;
   } else if (initialCpuCount > 32) {
```

So, the "Avg" bar in the top left of your screenshot is showing the aggregrate utilization across all CPUs.

In order to see individual processors you'll need to configure the exact layout you want (via F2/Setup -> Meters).
