### ISSUE TITLE
OpenBSD 7.3 htop showing wrong amount of RAM in use.

### ISSUE THREAD

**Issue by time-killer-games** [htop-dev/htop#1276]
These two code options are more correct it would seem.

This one returns the same amount for free RAM as regular 'top':
 ```
  int mib[2];
  mib[0] = CTL_VM;
  mib[1] = VM_UVMEXP;
  struct uvmexp buf;
  std::size_t sz = sizeof(buf);
  if (!sysctl(mib, 2, &buf, &sz, nullptr, 0))
    freeram = buf.free * sysconf(_SC_PAGESIZE);
```

...and so does this:
```
freeram = (sysconf(_SC_AVPHYS_PAGES) * sysconf(_SC_PAGESIZE));
```

The total RAM you have seems to be correct.  but when i do the math and return the total subtracted by the amount free I am not getting the same value with my test case I am with htop, despite getting the same amount in total as htop and the same amount of free ram as top. Reproducible: https://github.com/time-killer-games/ween

**Comment by Explorer09** [comment]
This report is hard to read. Do you have a definite steps to reproduce the problem or test data to compare side by side so that we can know which part of htop goes wrong?

**Comment by time-killer-games** [comment]
looked at the relevant code:

```
   Machine* host = &this->super;
   const int uvmexp_mib[] = { CTL_VM, VM_UVMEXP };
   struct uvmexp uvmexp;
   size_t size_uvmexp = sizeof(uvmexp);

   if (sysctl(uvmexp_mib, 2, &uvmexp, &size_uvmexp, NULL, 0) < 0) {
      CRT_fatalError("uvmexp sysctl call failed");
   }

   super->totalMem = uvmexp.npages * this->pageSizeKB;
   super->usedMem = (uvmexp.npages - uvmexp.free - uvmexp.paging) * this->pageSizeKB;
```

It would appear the problem is you are subtracting by uvmexp.paging. OpenBSD's system-provided [top(1)](https://man.openbsd.org/top.1) only shows the amount of free/unused RAM, which as mentioned already in my original report that would be equivalent to:

1) `uvmexp.free * this->pageSizeKB;`

and:

2) `sysconf(_SC_AVPHYS_PAGES) * sysconf(_SC_PAGESIZE);`

...as both equal the same thing at all times in my testing.

You can also run my test application I linked to and compare it with the results of htop and top.  my code show the same results as top, but not htop. To compile my test app on OpenBSD you need Xorg (which should be there by default), pkg-config, sdl2, and vim (for xxd). In my original post I cut out of my hundreds of lines of code the only part which mattered.

**Comment by Explorer09** [comment]
No. I don't have an OpenBSD machine to test it myself. So I requested you to provide more information on how to solve the issue.
What we really need right now is how to change the code to make it correct, in case you aren't used to filing a pull request on GitHub.

**Comment by time-killer-games** [comment]
No. Doesn't matter if you don't have an OpenBSD machine to test. I already told you what to change. :/ This is a one line change. If you are fine with taking my word for it that this change of mine is technically correct, that's fine by me. 

That said, I'll make a pull request, even though that's not technically why I submitted this issue.

**Comment by time-killer-games** [comment]
I'm going to test just real quick to be sure it doesn't break anything seemingly unrelated before I actually make the pr.

**Comment by Explorer09** [comment]
@time-killer-games 

> Edit: don't misread what I'm saying please. I am just confused why you are acting as though I have not given steps to reproduce or explained what needs changing when i have done both twice now.

Excuse me, but you really didn't give the steps to reproduce.
Most bug reports expect reproduce steps to be presented in numbered 1. 2. 3., and so that developers can reproduce the same problem as you experienced. Please don't expect the bugs would be obvious to the developers. Sometimes the "bugs" people reported are intended behaviors of the program, or just user's misunderstanding. That's why many projects require bug reports in certain formats. Notably, you should provide at least these three: "Steps to Reproduce", "Actual Results" and "Expected Results".

If you just throw in a project code of yours and expect we developers would compile and test, we would not bother (we need to find the same compiler toolchain as yours in order to test; this is too much work). And if you are already digging the code to find out which line went wrong, just submit a PR when you've done patching. This saves the time for both of us (you may have a particular way to fix the line of code; show us and we can save the time guessing).

**Comment by time-killer-games** [comment]
I don't know arguing against reality. You either can't read or don't care enough to and really need to calm down.

**Comment by time-killer-games** [comment]
Ignore my previous comments, including the one i just deleted, I have autism so i easily misread people, especially online. When i have time, i'll try to reformat this ticket and make it easier to digest. Hope everything is ok.

**Comment by time-killer-games** [comment]
@BenBE shouldn't this be closed, since the amount of ram you guys report is intended behavior?
