### ISSUE TITLE
"htop" is showing different ram usage compare to "top"

### ISSUE THREAD

**Issue by Oxygenxx** [htop-dev/htop#1302]
"**htop**" is showing different ram usage compare to "**top**"

i just want to understand what is the calculation/formula behind total ram usage

i tried this method 
( TotalUsage = MemTotal - MemFree - Cached - Buffers )      and   ( TotalUsage = MemTotal - MemAvailable ) 
using /proc/meminfo
but this total ram usage is still differs compare to htop total ram usage

![image](https://github.com/htop-dev/htop/assets/143133958/f132e44b-a2aa-41fd-a872-f02cd9d1b331)

I'll really appreciate you willingness to help to proved any answer in this direction 🙆🏻

**Comment by BenBE** [comment]
The value displayed by htop is the used plus compressed memory, excluding filesystem caches, I/O buffers or shared memory. Mostly all the memory that needs swapping if you need to push it out of RAM. Have a look at https://github.com/htop-dev/htop/blob/e79788c250c23e0c7c9f3e29fdca578ce9e9bca0/MemoryMeter.c#L28-L55 for the implementation details.

**Comment by time-killer-games** [comment]
This is the same issue on other platforms. The same thing I mentioned and noticed in my ticket:

https://github.com/htop-dev/htop/issues/1276

Since my ticket I saw it on Linux and NetBSD as well. I think it would personally be better if htop behaved the same as top in this regard, but you guys know way more about RAM usage than I do as I am fairly new to this area of study.

The only reason I said what I did was out of the limited understanding it would seem on the surface OS vendor's who actually write operating systems from scratch would seem to know more about RAM usage than third party developers who seem to think they have a better approach than OS developers. In any case, it would be interesting to know which approach is more technically correct and more useful to software developers and system admins who need to monitor their system's RAM usage for a variety of technical reasons, and hats off to htop devs if their approach happens to be right. :)

**Comment by time-killer-games** [comment]
> The value displayed by htop is the used plus compressed memory, excluding filesystem caches, I/O buffers or shared memory. Mostly all the memory that needs swapping if you need to push it out of RAM. Have a look at
> 
> https://github.com/htop-dev/htop/blob/e79788c250c23e0c7c9f3e29fdca578ce9e9bca0/MemoryMeter.c#L28-L55
> 
> for the implementation details.

Isn't another way of saying that just (wired page count + active page count) * page size? Because that seems to very consistently give me the same values in my own project and might be a simplified way of explaining that differently.

See the shell scripts I read output here, for example:
- https://github.com/time-killer-games/ween/blob/4c236cffdbde011c794be6eeb11253c82a5bc691/system.cpp#L786-L787
- https://github.com/time-killer-games/ween/blob/4c236cffdbde011c794be6eeb11253c82a5bc691/system.cpp#L793-L794

Seems very close to what htop produces, if not the same.
