### ISSUE TITLE
Name of container that contains a process

### ISSUE THREAD

**Issue by callumgare** [htop-dev/htop#1330]
Most of my workload is dockerised and so it would be super useful to have a new column to show the name of the docker container that a process belongs to (if it does indeed belong to one).

Whenever there's a resource usage issue like ram or cpu having a higher utilisation than expected my first port of call is htop to see what process is responsible. Generally it'll be something in a docker container since most stuff on my machines run in docker containers. So once I know what process or processes seem to be the cause of the trouble I then have to trace that back to the docker container they live in (unless it happens to be obvious and unambiguous from the process name). 

I do that by copying the PIDs of the relevant processes from htop then running:
```shell
pid=3728712 && docker ps --filter "ID=$(cat /proc/$pid/cgroup | grep -o -E '[0-9a-f]{10,}')" --format "{{.Names}}"
```
to find the name of the docker container it belongs too.

It would be great to just have "container name" as an optional column in htop. As well as being able to troubleshoot quicker it would also just be nice to have when everything going okay as well. I'd be able to look though htop and just from a glance get a sense of what containers make up the bulk of resource usage. I know [ctop](https://github.com/bcicen/ctop) sort of does this but I'd like to be able to see that at the process level and also to compare it to processes not in docker containers.

I had a look for similar issues and found https://github.com/htop-dev/htop/issues/1328 which is great to have but doesn't solve this situation wanting to easily get the human readable container name for a process (as well as to be able to super easily glance though the list and quickly identify what processes are containerised and which containers the most resource heavy processes live in).

Thanks for your consideration!

**Comment by BenBE** [comment]
As you noticed (re #1328 / #1329) there's a column called `CGROUP (compressed)` which reads the cgroup name for the process and does some heuristics on the cgroup name. This works for many container software quite nice (nspawn, lxc, with #1329 also podman), and a similar thing can be added for Docker too, as there's a [naming pattern](https://docs.docker.com/config/containers/runmetrics/). Now for the caveats: For cgroup v1, this will show Docker containers as LXC (which technically they are) and for cgroup v2 will only provide an container ID (which should be shortened to a sensible level for display). But that's just part of the issue at hand.

What this issue is actually about is a separate column for this, and the existing code could be updated to filter out any non-container parts of the cgroup path. This will create quite a bit of code duplication for that column though …
