### ISSUE TITLE
Feature request: CPU-Temp and other sensor-temperatures

### ISSUE THREAD

**Issue by ohunecker** [htop-dev/htop#232]
Current temperatures from the system sensors would be awesome. 
Something like [htop with CPU Freq and CPU Temp](https://github.com/avafinger/htop)

![arm64-htop-2 1 0-2](https://user-images.githubusercontent.com/244878/95558201-2a4a4200-0a16-11eb-934d-30c954d95f15.png)

**Comment by cgzones** [comment]
There is an option (`F2 -> Display Options -> Also show CPU frequency`) to show the frequency of a CPU core inside the CPU bar (where is the above image currently only the utilization is shown).
But (yet) no extra Meter to show the avg/median/max/min frequency.

See #93 and #111 for displaying the CPU temperature.

**Comment by ohunecker** [comment]
Greate!! 
Next time i will look into open pull requests too, before i start a new feature request.
I will now wait for next merge.

**Comment by Ark74** [comment]
Starting in what version is this feature available?

**Comment by BenBE** [comment]
> Starting in what version is this feature available?

`libsensors` support was added in version 3.0.3 (Dec 2020, originally added in 1b225cd7a0af03a6349c48326118a287fc36acd0). Several updates and improvements have happened since.

The screenshot at the top of this issue shows an unsupported fork based on htop 2.2.0 on Armbian that introduced several patches for which I described their (lack of) quality [here](https://github.com/htop-dev/htop/issues/523#issuecomment-820142977) …

**Comment by fasterit** [comment]
After feedback from @ginggs on IRC regarding the lack of core temps on recent AMD CPUs (#806, #856), I think we should offer such a CPU temp meter for those users. AMD does not seem to expose core temps at the moment.

**Comment by Cysign** [comment]
Is it possible to display the current temp and max temp on a Raspberry? How would I set this up?
