### ISSUE TITLE
Applying Light Terminal Color letters are black in black background

### ISSUE THREAD

**Issue by giannakopoulosj** [htop-dev/htop#279]
Hello,
When selecting Colors  **F2->Setup(Colors)->Light Terminal** the background changes to black and the letters color remaining black. Thus black letters on black background it becomes unreadable. (Screenshot provided below)
It seems that this behavior is not expected. Could the black letters change to green? (As per process remaining letters that showing in screenshot)
Using htop 3.0.2 RHEL 7.8

![image](https://user-images.githubusercontent.com/2518387/96968981-74551c80-151a-11eb-8506-33d650374708.png)

![image](https://user-images.githubusercontent.com/2518387/96968452-aca82b00-1519-11eb-8e6d-6c8f625a78cb.png)

**Comment by BenBE** [comment]
The Light Terminal style is intended for terminals with a light/white background.
If your terminal has indeed white background, but starting htop paints it black, then this is a bug. Otherwise, if your terminal usually has black background, this is as intended (though the default could be dark grey for text). ;-)

**Comment by giannakopoulosj** [comment]
Indeed the terminals background is black. Since this is expected i don't think a change to gray should be made just to satisfy terminals with black bg. if you agree i will proceed and close this one.

**Comment by cgzones** [comment]
I think this is an actual bug and should be fixed by https://github.com/htop-dev/htop/commit/4b14ab9789eee004daab8594ac00a113c18af060 :thinking:

**Comment by giannakopoulosj** [comment]
Since 4b14ab9 has been merged on master and be fixed on new release i will close this issue.

**Comment by deviant** [comment]
No, that was the correct behaviour. This is how it's supposed to look:

![20210108_010035](https://user-images.githubusercontent.com/68829907/103959714-bcb2cc80-5150-11eb-97b2-3f165590f479.png)

As @BenBE said, it's intended for people using a light background and will naturally appear broken if you're not using one. It exists because the default colour scheme is similarly broken when using a light terminal. (It's like the "Black on White" colour scheme, except the background is default.)
