### ISSUE TITLE
bring back the regular checkmarks

### ISSUE THREAD

**Issue by Ckath** [htop-dev/htop#29]
![pls](https://user-images.githubusercontent.com/15038414/91637229-a3598100-e9f6-11ea-9c25-ffd702e0eebb.png)
its great and all this is still maintained, but I dont enjoy things becoming less readable. you could argue here "use a better font" but htop is used in a lot of minimal installs that might be lacking all and any fancy glyphs, which is why the old method of checkmarks is used in nearly every cli program

**Comment by Arkanosis** [comment]
I have to agree there. As much as I like using dedicated glyphs in most places, I have a hard time telling whether a box is checked or not since 3.0.

BTW, thanks for taking over maintainership!

**Comment by Ckath** [comment]
to add on to this as I just noticed, in TTY the symbol is exactly the same for checked and unchecked with these new glyphs

**Comment by Arkanosis** [comment]
> to add on to this as I just noticed, in TTY the symbol is exactly the same for checked and unchecked with these new glyphs

Oh, you're right. Not sure how I could take a screenshot of a TTY, but I get an identical small blue square for both checked and unchecked boxes. That's probably because I use the `sun12x22` console font, but that's not something I can change without breaking a lot of other stuff.

**Comment by bertwesarg** [comment]
Very unfortunate to hear, that this is not appealing on all terminals, fonts, or sizes. Though I'm not sure that removing the feature completely is the way to go. We may can add an option to disable the use of UTF-8, even though the terminal supports it. But this would also effect the UTF-8 characters for the tree view.

**Comment by Ckath** [comment]
> Very unfortunate to hear, that this is not appealing on all terminals, fonts, or sizes. Though I'm not sure that removing the feature completely is the way to go. We may can add an option to disable the use of UTF-8, even though the terminal supports it. But this would also effect the UTF-8 characters for the tree view.

I dont think anyone ever complained about the utf8 tree chars, as they are regular box drawing chars that exist in most if not all fonts used. I considered adding a way to have the settings structure in CRT.c where its set, and allow user overwrites for what they want utf8 or ascii. even if that was added, it doesnt seem ideal(wont live update) and also not worth the effort as everyone was completely okay with the ascii/utf8 situation as it was (characters for trees but not checkboxes).

thus simply making it act like it has done for years seemed the easiest solution.

**Comment by Arkanosis** [comment]
Yeah, UTF-8 is fine for the tree view, and is fine for most characters as well (let's say I have some `fôöbâr.sh` running; it's displayed properly in htop even within a TTY). Having to disable UTF-8 altogether would be a regression. So far, the only problem I've seen is with the checkboxes.

**Comment by Ckath** [comment]
should add that the whole "utf8" detection seems like a bit of nonsense to begin with as box drawing chars used for tree are within the ascii table as well

**Comment by xfix** [comment]
I believe using Unicode ballot boxes and check marks was a mistake. If you check `wcwidth(L'☑')` it will provide `1` as answer (at least that's what happens on my operating system). This means that a check mark will take 1 character of space in a terminal.

Now, consider that this character is rendered as a square. In many fonts, the height of a character is twice as big as its width. However, because ballot box is a square its size is going to be affected by its width, resulting in a tiny character.

On systems where `wcwidth(L'☑')` is 2 (maybe macOS? surely it didn't look too bad for whoever submitted this patch) I think this rendering is fine, but when `wcwidth(L'☑')` is 1 it's going to be pretty bad.

**Comment by chrisduerr** [comment]
I'd like to point out that box drawing characters aren't even UTF-8 necessarily. There's a dedicated character set for box drawing characters that the terminal can switch to for those (character set `0`). So you can easily use those without UTF-8 support, just by using ascii.

**Comment by bertwesarg** [comment]
Let me give you a little more context, why I choose to switch to the UTF-8 check boxes:

I added the toplogy view to the affinity panel ('a'). This shows the hardware topology in a tree to easily select the sup-trees for the affinity mask. Thus there is a tree and for each tree entry a check box. I looked at the process tree, which also allows to collapse process children. But I was rather disappointed about the use of `+` for the state of a collapsed tree node:

Here is the _opened_ state, i.e., show _process children_, which uses the BOX DRAWINGS LIGHT HORIZONTAL as the `-`

```
├─ x
│  └─ y
└─ z
```

Here is the _closed_ state, which uses the ASCII `+`:

```
├+ x
└─ z
```

As you can (hopefully) see, the horizontal line of the `+` does not align with the box drawing character.

I therefor searched for a better solution in the Unicode charset, but did not found a better one. But I found the checkbox code points and also code points for `⊟` and `⊞`. I considered these superior to the ASCII check boxes. Because the affinity panel is very prone to have an excessive panel width, if the hardware topology gets too complex. The unicode codepoints could save here valuable screen estate, in contrast to the ASCII `[x]` and `[+]`/`[-]`version.

The ASCII version has a nonlabel width of of 4 (check box) + (3 * hierarchy depth) (tree drawing) + 4 (tree open/closed). While the Unicode version has only a non-label width of 2 + (3 * hierarchy depth) + 2. Thus the width is 4 characters more narrow.

I have now found, that Unicode 13 has a new code point for a [horizontal line with a stroke](http://www.fileformat.info/info/unicode/char/1fbaf/index.htm) which should provide an aligned `+`. Thus reverting to process tree variant for closed/opened sub-trees, should be possible and thus would not require the extra `⊟` and `⊞`. Resulting in a non-label width of 4 (ASCII check box) + (3 * hierarchy depth) (tree drawing). Thus is the same as with the current Unicode implementation.

I will therefor create a merge request, which reverts to ASCII only check boxes and to the same tree as the process tree for open/closed. And will also add an option to use the new U+1FBAF code point, instead of the `+`. Though I'm not sure, if it is possible to add an configure check for this.

**Comment by Ckath** [comment]
> As you can (hopefully) see, the horizontal line of the + does not align with the box drawing character.

so then dont use the `+` when you want it to lign up with box drawing chars, theres stuff like `ACS_PLUS` or any of the other box drawing things that couldve been used here.
![image](https://user-images.githubusercontent.com/15038414/91669663-1c93c980-eb06-11ea-8a5f-940d3b3357fe.png)

>valuable screen estate

its not so much a matter of screen realestate as it is readability, its a mess to have these unicode things inside a 99% ascii ui, it'll never line up or look right. for example, this is how great these 'superior' symbols are going to look for me:
![image](https://user-images.githubusercontent.com/15038414/91669729-c1160b80-eb06-11ea-86af-57fb933c5722.png)

**Comment by AlexandraAalto** [comment]
My terminal entirely lacks the checkbox characters, replacing them with identical placeholders thus making the option screen unusable.

**Comment by AlexandraAalto** [comment]
My terminal entirely lacks the checkbox characters, replacing them with identical placeholders thus making the option screen unusable.

**Comment by bertwesarg** [comment]
> > As you can (hopefully) see, the horizontal line of the + does not align with the box drawing character.
> 
> so then dont use the `+` when you want it to lign up with box drawing chars, theres stuff like `ACS_PLUS` or any of the other box drawing things that couldve been used here.
> ![image](https://user-images.githubusercontent.com/15038414/91669663-1c93c980-eb06-11ea-8a5f-940d3b3357fe.png)

this large plus is _large_, i.e., it touch the upper and lower lines. that just lokkd as ugly as the ASCII plus

> 
> > I will therefor create a merge request, which reverts to ASCII only check boxes and to the same tree as the process tree for open/closed. And will also add an option to use the new U+1FBAF code point, instead of the +. Though I'm not sure, if it is possible to add an configure check for this.
> 
> step in the right direction though I would highly prefer it just all being ascii and all and any unicode being the optional enable. as the code is currently I only see settings taking effect after a restart with how CRT.c is structured. instead of setting it there once, just checking a setting value wherever it is used might work out.

the only Unicode left (AFAICS) would be the tree box drawing characters, and you also want to have a dynamic option just for these?

**Comment by bertwesarg** [comment]
> > > As you can (hopefully) see, the horizontal line of the + does not align with the box drawing character.
> > 
> > 
> > so then dont use the `+` when you want it to lign up with box drawing chars, theres stuff like `ACS_PLUS` or any of the other box drawing things that couldve been used here.
> 
> this large plus is _large_, i.e., it touch the upper and lower lines. that just lokkd as ugly as the ASCII plus
> 

here is an impression of your `ACS_PLUS` proposal:

![Screenshot at 2020-08-31 07-17-00](https://user-images.githubusercontent.com/111934/91685298-3d860a00-eb5a-11ea-9d0f-2adb344b7e5d.png)

**Comment by bertwesarg** [comment]
there is one problem with the tree drawing though, the root node (`init` or `systemd`) does not have any tree drawings and thus is not able to indicate whether this node is collapsed or not, see here:

![Screenshot at 2020-08-31 07-53-43](https://user-images.githubusercontent.com/111934/91687031-1c73e800-eb5f-11ea-9e3b-0840e80c42e3.png)

![Screenshot at 2020-08-31 07-52-32](https://user-images.githubusercontent.com/111934/91686968-f2222a80-eb5e-11ea-8289-033006e37af2.png)

This is for the process tree not that important, but for the topology it may look a little weirder:

![Screenshot at 2020-08-31 07-58-48](https://user-images.githubusercontent.com/111934/91687404-e84cf700-eb5f-11ea-934e-058519379cbb.png)

![Screenshot at 2020-08-31 07-59-08](https://user-images.githubusercontent.com/111934/91687438-fa2e9a00-eb5f-11ea-82da-dd5d25382b2e.png)

Any suggestions, if this needs improvements?

**Comment by natoscott** [comment]
@bertwesarg @Ckath we're putting together a little 3.0.1 with fixes-only very soon - if you folks can agree on a path forward here and send a PR asap, that'd be great.

This is the current proposal AFAICS - https://github.com/htop-dev/htop/pull/39 - but it looks like its not taking into account discussion here so far.

Thanks!

**Comment by eworm-de** [comment]
The origin repository has a long standing pull request to disable unicode at runtime:
https://github.com/hishamhm/htop/pull/215/commits/d89fd2dd9bc5aa647396c766e4150727b82dd3a7

I've wanted this to replace braille characters with ascii chars (for graph meters) when in terminal.
I could rebase the patch, then make the check boxes use this settings as well.

**Comment by Ckath** [comment]
> here is an impression of your `ACS_PLUS` proposal:
> 
> ![Screenshot at 2020-08-31 07-17-00](https://user-images.githubusercontent.com/111934/91685298-3d860a00-eb5a-11ea-9d0f-2adb344b7e5d.png)

I see the issue, I suppose suffixing it with some other random middle alligned symbol wont make it super clear either, this would leave things like `[+]`. I should also mention that in my terminal font and supposedly others just a regular `+` ligns up and looks fine.

> there is one problem with the tree drawing though, the root node (`init` or `systemd`) does not have any tree drawings and thus is not able to indicate whether this node is collapsed or not, see here:
> 
> ![Screenshot at 2020-08-31 07-53-43](https://user-images.githubusercontent.com/111934/91687031-1c73e800-eb5f-11ea-9e3b-0840e80c42e3.png)
> Any suggestions, if this needs improvements?

if you hadnt mentioned it I would've probably never noticed, could always prefix it with the collapsed indicator of choice if its too unclear, or maybe put it at the end.

**Comment by Ckath** [comment]
> The origin repository has a long standing pull request to disable unicode at runtime:
> [hishamhm/htop@d89fd2d](https://github.com/hishamhm/htop/commit/d89fd2dd9bc5aa647396c766e4150727b82dd3a7)
> 
> I've wanted this to replace braille characters with ascii chars (for graph meters) when in terminal.
> I could rebase the patch, then make the check boxes use this settings as well.

I was going to say "it might be nicer to keep it all in settings" but it seems like `--no-mouse` is the same deal with it both being in settings and as a flag. so I'm not really sure what the actual convention is with these types of things. at the very least I think it'd also make sense to keep the unicode/ascii choice a setting as well as people will probably want to run one all the time.

**Comment by bertwesarg** [comment]
> > there is one problem with the tree drawing though, the root node (`init` or `systemd`) does not have any tree drawings and thus is not able to indicate whether this node is collapsed or not, see here:
> > Any suggestions, if this needs improvements?
> 
> if you hadnt mentioned it I would've probably never noticed, could always prefix it with the collapsed indicator of choice if its too unclear, or maybe put it at the end. to add to this not mattering much, top also doesnt bother indicating collapsed top level nodes

I have now only the '+' and '-' as a prefix for the root node.

![Screenshot at 2020-08-31 21-42-21](https://user-images.githubusercontent.com/111934/91760156-233c4280-ebd3-11ea-80ba-41f625cf2fac.png)

![Screenshot at 2020-08-31 21-42-45](https://user-images.githubusercontent.com/111934/91760168-2800f680-ebd3-11ea-90a4-230354e3d906.png)

Nothing changes for sub-nodes. I'm pretty satisfied with this.

**Comment by Ckath** [comment]
> I have now only the '+' and '-' as a prefix for the root node.
> 
> ![Screenshot at 2020-08-31 21-42-21](https://user-images.githubusercontent.com/111934/91760156-233c4280-ebd3-11ea-80ba-41f625cf2fac.png)
> 
> ![Screenshot at 2020-08-31 21-42-45](https://user-images.githubusercontent.com/111934/91760168-2800f680-ebd3-11ea-90a4-230354e3d906.png)
> 
> Nothing changes for sub-nodes. I'm pretty satisfied with this.

seems to work out great!
