### ISSUE TITLE
Release tarballs?

### ISSUE THREAD

**Issue by dylanaraps** [htop-dev/htop#31]
Software built with autotools is typically released with tarballs containing the already generated configure script and friends. This was also true of htop prior to this fork. Will this practice be continued here?

**Comment by avindra** [comment]
+1

Otherwise, we would have to adopt in a similar fashion to Arch linux:

https://github.com/archlinux/svntogit-packages/blob/packages/htop/trunk/PKGBUILD#L27

Running `autoreconf` is considered an anti-pattern for this build toolchain, from what I understand.

**Comment by natoscott** [comment]
I've created: https://bintray.com/htop/source/htop
and there's direct tarball links at https://dl.bintray.com/htop/source/

**Comment by dylanaraps** [comment]
Both `curl` and `wget` give me a 404 error when trying to download the source. Firefox works fine however.

```sh
# package manager calling curl
-> htop Downloading https://dl.bintray.com/htop/source/:htop-3.0.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

```
# basic wget on commandline
-> wget https://dl.bintray.com/htop/source/:htop-3.0.0.tar.gz
Connecting to dl.bintray.com (52.57.5.200:443)
wget: server returned error: HTTP/1.1 404 Not Found

```

**Comment by natoscott** [comment]
The 'Set Me Up' link on https://bintray.com/htop/source/ explains how to invoke curl to download these files.

**Comment by dylanaraps** [comment]
Yeah. The package manager I am using does include `-L` and `-o` in its call to `curl`. This still results in 404 errors when attempting to download the sources (specifically: https://dl.bintray.com/htop/source/:htop-3.0.0.tar.gz).

**Comment by natoscott** [comment]
You seem to have a stray colon in there.  Cut & paste the instructions on 'Set Me Up', maybe, and then insert the filename you seek ("htop-3.0.0.tar.gz").

**Comment by dylanaraps** [comment]
This colon is in the link here: https://dl.bintray.com/htop/source/ 

I didn't add the colon to the source.

**Comment by dylanaraps** [comment]
The link works now, thanks. The link on the above page should be fixed no?

**Comment by natoscott** [comment]
> The link works now, thanks. The link on the above page should be fixed no?

Yep - looks like that may be a bintray.com bug.  I'll send them a note.

**Comment by abbeyj** [comment]
I know this issue is marked Closed but I think there may still be work to do here.  Let me know if you'd prefer a new issue be opened instead.

- https://htop.dev/downloads.html has a link at the top to "Latest Release".  That takes you to https://bintray.com/htop/source/htop.  I can't figure out how to download anything from this page.  Under "Downloads (ver: 3.0.0)" it says "No direct downloads selected for this package."  Clicking on the link "3.0.0" takes you to https://bintray.com/htop/source/htop/3.0.0 but that page also reports no downloads are available.  Clicking "Set me up" gives you instructions for using curl but it requires you to already know the filename that you want and that filename is not listed on the page.
- If you go down the page to https://htop.dev/downloads.html#sources, it says that the instructions for building are "./configure; make; sudo make install".  Then it provides a link to the "official tarball" which links to https://github.com/htop-dev/htop/releases.  But that tarball doesn't have a configure script in it.

Which is the "official" location of the source, bintray.com or github.com?  Why provide a link to one place in one location and a link to the other in a different location?  If the github.com location is to be the official source then it either needs to include a configure script or the instructions need to change.  If the bintray.com location is to be the official source then shouldn't you stop linking to github.com here?
