### ISSUE TITLE
Vim keys break search

### ISSUE THREAD

**Issue by ilyazzz** [htop-dev/htop#34]
When searching for a process with vim keys enabled, you cannot use HJKL keys. It instead closes the search box and starts navigating instead.

**Comment by Ckath** [comment]
ontop of this `n` also doesnt do next item in results. htop's search isnt 1:1 with vim to begin with because you cant 'confirm' a search and then go through results, it closes the search window after pressing enter. so maybe it'd make the most sense to disable navigation keys while in search and use something like `shift`+`n` or `ctrl`+`n` to iterate over results?

**Comment by fasterit** [comment]
Has been resolved in two ways: Fixing the search function and later removing he vim key option altogether (too much collateral damage).

**Comment by freed00m** [comment]
Can I politely ask, how to enable these vim keybindings? I am looking in man page and searching online to no avail. 
All I can find is forks.

**Comment by fasterit** [comment]
You can't, see comment above: "... and later removing the vim key option altogether (too much collateral damage)."
There is an unfinished PR at #141 to try and implement a better vim mode.

**Comment by BenBE** [comment]
Which doesn't mean, that there are at least some key bindings in `htop` that are heavily inspired by `vim`: The (incremental) search is reachable both with <kbd>F3</kbd> and <kbd>/</kbd>, which is as close to `vim` as you can get …

FWIW: As there are situations when keyboard mappings outside the ASCII range won't work properly there's usually also a fallback for that situation provided. If it makes sense, this fallback tries to use keys similar to those found in `vim`, but that's usually not the target. See the keys listed on the <kbd>F1</kbd> screen.
