### ISSUE TITLE
How to display CPU temperature

### ISSUE THREAD

**Issue by aurelijusrozenas** [htop-dev/htop#358]
Hi.

Most likely a stupid question but what are the prerequisites for CPU temperature display? I see both https://github.com/htop-dev/htop/pull/93 and https://github.com/htop-dev/htop/pull/111 are merged but I not see anything with temperature in meters or display options.
I have libsensors5 and lm-sensors installed. Compiled htop from source. System is x64 Ubuntu 20.04.1.

**Comment by BenBE** [comment]
You need to `./configure` with `--enable-sensors`.

When running `htop` with this build-time configuration set you should see two options related to temperature in the `F2 Setup` menu under `Display options`: Namely `Also show CPU temperature` and `- Show temperature in degree Fahrenheit instead of Celsius`.

The temperature display will then be part of the normal CPU meters.

**Comment by aurelijusrozenas** [comment]
Oh, thanks for quick response!
Of course it is configuration option! I mean - I had no idea :) Ok, it works, great.
For the record I also needed `libsensors4-dev`.
Thank you.
