### ISSUE TITLE
"secure" mode or flag

### ISSUE THREAD

**Issue by jeroenhabets** [htop-dev/htop#483]
Logged previously by @mmcco as [#350 in the old repo](https://github.com/hishamhm/htop/issues/350)

> Most people use programs like htop only for passive system monitoring. This means that, after startup, htop will usually only call the sysctls and ioctls necessary to gather information, and then print that information to the screen. htop can therefore be easily locked down with a privilege reduction mechanism.
> 
> A few OpenBSD devs recently did this with less(1). If you scroll down, you'll see that less disables many features if the environment variable LESSSECURE is set to 1 on startup. This allows us to use pledge(2) more restrictively.
> 
> Is there interest in a feature like this? I'd like to work on it.

My use case is described quite well in @decadent 's [comment](https://github.com/hishamhm/htop/issues/350#issuecomment-546653878): 
> It's getting pretty tiring to type the password every time, so I'd like to put htop in sudoers, but preferably with a flag that would disable killing processes or modifying priorities (not sure what other operations htop can do).

**Comment by BenBE** [comment]
Part of this self-restriction is already done in #79 that was recently merged for 3.0.6. While this does not introduce a "read-only" mode in itself, it reduces the damage that people can do when getting code execution in `htop`.

Possible routes to go forward are two-fold. The first one that comes to mind is boot-strapping htop into its own seccomp sandbox and sharply limiting the allowed syscalls to the bare minimum needed. While this gives the most restrictive results it's also a solution that will be highly dependent on the system environment htop is running on. Also this is limited to Linux when going the route of using seccomp. Also depending on the restrictions of imposed by seccomp itself (not sure, if the no-malloc restriction in Chrome e.g. comes from seccomp or their implementation of the sandbox).

The second way is actually implementing a read-only mode for htop. With this in mind, you'd actually end up having to maintain two feature sets for htop to hold: one required in normal operation and another for the read-only mode. With the patchset from #79 this results in 5 sets of capabilities to keep, where even with the read-only restriction certain capabilities like `CAP_PTRACE` would still have to be kept, as reading certain information requires htop to hold on to this capability.

Which brings us to the scope of the sandboxing: Given how bad you can already control, which memory ncurses holds, don't even bother determine which files it will try to access; like e.g. terminal descriptions, locales, … Not to mention all of these are highly dependent on your distribution, thus won't come without quite a bit of maintainance effort that has little to do with core htop functionality. Probably it's easier to just got for something existing like [firejail](https://github.com/netblue30/firejail) and write a small descriptor file that manages to not interfere with normal htop operation on your system …

**Comment by decadent** [comment]
I had a simpler approach in mind: just a bunch of `if`s forbidding potentially destructive features when a flag is set. IMO this would work if the program is installed with the permissions of the root user and can't be replaced by a regular user. However, on further thought, Homebrew on Mac installs programs and libraries under regular users, and if Htop uses a library from Homebrew then it could still be infiltrated. So I guess the approach would depend on Htop being compiled statically (or installed somewhere like /opt together with libraries it uses, but I believe that's functionally the same as static compilation, only probably more compilcated).

Perhaps then, on Mac, Htop could detect if it's compiled statically—maybe via a compile-time flag?—and permit the restricted mode only in a static installation, so that users wouldn't potentially shoot their legs with libraries by installing a packaged distribution.

Dunno if this solution is any good, but if sandboxing and capability-limiting is too involved then this might be a more immediate approach, though not quite as thorough.

It might be questioned whether this restriction is any use on Mac when a malware under a regular user can already write anywhere it wants, outside of the OS itself—but I would hope, at least, that it would prevent rogue programs from installing a keylogger or circumventing malware scanners—supposing that root permissions would grant any such abilities.

**Comment by BenBE** [comment]
I don't think the approach to limit functionality based on compilation settings is any good, when all it takes is for the user to have a compiler and recompile without those restrictions.

The options implemented by #79 are not meant to limit what malware on the system can do, but rather limit the available attack surface within `htop` in such a way that even when you manage to get code execution within `htop`, you can't do any more harm than you could do with the privileges that `htop` requires for its normal job; even if the user that runs `htop` usually would have a whole bunch more.

When malware runs on your system you should fix your system.

**Comment by cgzones** [comment]
I think the initial use case was allowing regular users via a sudo rule to run htop with root privileges, to be able to gather all data, but not be able to change/modify any process/system state.
[ncdu(1)](https://manpages.debian.org/unstable/ncdu/ncdu.1.en.html) has a similar option: `-r/-rr`.
And when executing htop via sudo, there should not be loaded any user supplied library.

**Comment by decadent** [comment]
Indeed, my scenario is that I want to put htop in `sudoers`—but then, if it has abilities to modify programs' state or run programs or shell commands then it becomes a potential privileges-escalation route. I'd like very much to be able to squash malware immediately if it invades the system, but alas so far software is quicker than me.

> I don't think the approach to limit functionality based on compilation settings is any good, when all it takes is for the user to have a compiler and recompile without those restrictions.

That would also require the ‘user’ (i.e. malware) to replace the existing htop binary that's specified in `sudoers`, but as I suggested, I would `chown` that to root beforehand so that I know it's not replaced without my authorization.

**Comment by BenBE** [comment]
The only tractable way IMO is the way `ncdu` does with its "read-only" mode.
And maybe to be extra sure, also try to drop additional privileges not needed in that case (extension to #79).
