### ISSUE TITLE
Feature request: add temperature support patch?

### ISSUE THREAD

**Issue by cristianocang** [htop-dev/htop#49]
Hi

It is possible to add the temperature patch, so the AUR package [htop-temperature](https://aur.archlinux.org/packages/htop-temperature/) won't be needed anymore?

The patch itself is available [here](https://aur.archlinux.org/cgit/aur.git/tree/htop-temperature.patch?h=htop-temperature).

Thank you very much!

**Comment by natoscott** [comment]
@cristianocang makes sense to me (htop already reports battery status).  Could you request the original code author(s) open a pull request on this git repo?  Thanks!

**Comment by cristianocang** [comment]
Just did it! I hope the author of the patches answers soon.

**Comment by DX37** [comment]
Hey there, DragonX256 from AUR here. I'll create pull request now.

**Comment by DX37** [comment]
So, should #93 resolve this issue, or #111?

**Comment by DX37** [comment]
So issue closed with no discussion which implementation should be included, but variant, created by one of the main developers is preferred? Cool, cool...
@natoscott, I don't understand.

**Comment by DX37** [comment]
Okay, just saw mention in commit.
You would at least say that you chose a different implementation, not just quiet merge/close.

**Comment by fasterit** [comment]
@DX37 I tried to express exactly that by merging one and closing the other.
I explicitly thanked you because your implementation and inspiration made somebody else provide a superior implementation. That should make you proud, it is the way open source is meant to work. And I tried to express the core team's gratitude for your leadership in this. I'm sorry you did not receive the message as intended.
