### ISSUE TITLE
[Regression] Htop >= 3.0.3 does not list any processes

### ISSUE THREAD

**Issue by Nuc1eoN** [htop-dev/htop#534]
On GoboLinux, since version 3.0.3 htop's process list is empty for me. I have also tried the latest version 3.0.5.

Any release prior to that works as expected. Bug reference: https://github.com/gobolinux/Recipes/issues/111 (you will find some logs there)

(Ncurses v6.2, Linux 5.6.10)

**Comment by cgzones** [comment]
Is the header correctly shown?
Can you search for `"/proc"` in your strace log?

**Comment by BenBE** [comment]
@Nuc1eoN : Can you please try a `git bisect` between versions 3.0.2 and 3.0.3? This should take about 8-10 compile/test cycles.

To start clone this repository and run the following commands:
```bash
git clone 'https://github.com/htop-dev/htop' htop-test
cd htop-test
git bisect start
git bisect good 3.0.2
git bisect bad 3.0.3
```

After this run the following steps until `git` gives you a definitive result:
```bash
git clean -fdx
./autogen.sh
./configure
make
./htop
```
When running `htop` check if the bug is present. If the version of `htop` works fine, run `git bisect good`, if it shows the bug you describe, run `git bisect bad` or if things go wrong - like compilation fails - run `git bisect skip`. After about 8-10 of these steps you should get a long message showing the first commit that shows the reported issue. Place report this hash and details you deem important for further diagnosis (e.g. when error behaviour slightly changed across tries).

After you finished the bisection you can leave bisect mode by running `git bisect reset`.

For best results try to model the `configure` command as closely to that used by your distribution as possible. Narrowing down certain features from the set of `configure` options may also be of great help.

TIA.

**Comment by fasterit** [comment]
`Compile htop` on GoboLinux 017 installs htop 3.0.4 at the moment.
This version is not functional.
```bash
cd /Data/Compile/Sources/htop-3.0.4
./configure --with-proc=/proc/
make
```
yields a functional version. So @cgzones suspicion is confirmed.
I had to do the same to get a functional build on Debian's Hurd port (cf. https://salsa.debian.org/debian/htop/-/commit/3985adac5b6b886f3225ee6fb8cba838d1a84b15).

The reason seems to be that we open PROCDIR with O_NOFOLLOW:
GoboLinux 017 gets `-1 ENOTDIR` on `openat(AT_FDCWD, "/proc", O_RDONLY|O_NOFOLLOW|O_DIRECTORY)` with the default configuration of `/proc`.

GoboLinux should update its recipe as it mounts `proc` on `/System/Kernel/Status` and compiling after `./configure --with-proc="/System/Kernel/Status"` yields a working version.

If we drop the `O_NOFOLLOW`, symlinked `/proc` directories work.

But there is probably sometime more fishy with (our use of?) `openat`:
From `man 2 openat`
<pre>ENOTDIR
    pathname is relative and dirfd is a file descriptor referring to a file other than a directory.</pre>

apparently `/proc` is interpreted as relative to `AT_FDCWD` in the presence of a `/proc` symlink. `/proc/` is not.

/DLange

**Comment by Nuc1eoN** [comment]
I can confirm adding `--with-proc=/proc/` is a valid workaround.

**Comment by rubyFeedback** [comment]
Sounds like a useful work around. GoboLinux is actually, despite claims to the contrary,
compatible to FHS as-is. E. g. /proc/ is just a symlink not shown by default (they can
use gobohide/unhide to show it as is; in fact I was using GoboLinux as a FHS distribution
by flat-out compiling into /usr as-is - and that worked too just fine! So many people have
never used GoboLinux yet still make strange claims on reddit in particular.)

Support for GoboLinux should be retained because hisham, former main author
of htop, started GoboLinux a long time ago. :D Let's not forget legacy!

PS: Ncurses still annoys me sooooo much ... they should have really made compiling
it so much simpler. I love htop but I really hate ncurses. Any modern GUI is so much
nicer to work with than ncurses.

**Comment by bolemo** [comment]
For info: same exact issue (symptoms) appeared on htop 3.0.3 and up with Entware: https://github.com/Entware/Entware/issues/627

I tried the `--with-proc=/proc/` but it does not work there, as /proc does not seem to be a symlink.
I also removed `O_NOFOLLOW` from source code, without success.

**Comment by fasterit** [comment]
What mount point does `proc` have then (see `mount  | grep "type proc"`)?

Does it work if you build it with that mount point?

**Comment by bolemo** [comment]
> What mount point does `proc` have then (see `mount | grep "type proc"`)?
> 
> Does it work if you build it with that mount point?
```
root@HERMES:~$ mount | grep "type proc"
proc on /proc type proc (rw,relatime)
```

**Comment by zyxmon** [comment]
`ac_cv_func_openat=no` solved the problem on another device.

**Comment by nuno-silva** [comment]
I'm seeing an empty process list after upgrading from htop-3.0.2 to htop-3.0.5 ([ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-process/htop/htop-3.0.5.ebuild?id=d65d18def19679cae4c4b0f23abceb6c0eef7182)), using Gentoo Linux on armv7 (linux 3.4), where `/proc` is a procfs. Weirdly enough, this does **not** happen on my amd64 (linux 5.12), also procfs.

![image](https://user-images.githubusercontent.com/6935057/121253430-012dca00-c8a1-11eb-8cce-2b72bf721796.png)

Using strace, I can see it's opening `/proc` with no problem and seems to be able to list pids there:
```c
access("/proc", R_OK)                   = 0
...
openat(AT_FDCWD, "/proc", O_RDONLY|O_NOFOLLOW|O_DIRECTORY) = 3
fstat64(3, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
fcntl64(3, F_GETFL)                     = 0xc000 (flags O_RDONLY|O_NOFOLLOW|O_DIRECTORY)
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
getdents64(3, 0xb8985548 /* 261 entries */, 32768) = 7320
openat(3, "1", O_RDONLY|O_NOFOLLOW|O_PATH|O_DIRECTORY) = 4
openat(4, "task", O_RDONLY|O_NOFOLLOW|O_DIRECTORY) = 5
```
but then I see a lot of `EBADF` like this:
```C
fstat64(5, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
fcntl64(5, F_GETFL)                     = 0xc000 (flags O_RDONLY|O_NOFOLLOW|O_DIRECTORY)
fcntl64(5, F_SETFD, FD_CLOEXEC)         = 0
brk(0xb89b6000)                         = 0xb89b6000
getdents64(5, 0xb898d738 /* 3 entries */, 32768) = 72
getdents64(5, 0xb898d738 /* 0 entries */, 32768) = 0
brk(0xb89ae000)                         = 0xb89ae000
close(5)                                = 0
openat(4, "io", O_RDONLY)               = 5
read(5, "rchar: 19762850622133\nwchar: 765"..., 1023) = 163
read(5, "", 860)                        = 0
close(5)                                = 0
openat(4, "statm", O_RDONLY)            = 5
fcntl64(5, F_GETFL)                     = 0 (flags O_RDONLY)
fstat64(5, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(5, "453 77 70 9 0 72 0\n", 1024)   = 19
close(5)                                = 0
openat(4, "stat", O_RDONLY)             = 5
read(5, "1 (init) S 0 1 1 0 -1 1077936384"..., 2048) = 268
read(5, "", 1780)                       = 0
close(5)                                = 0
fstat64(4, 0xbe9f58c8)                  = -1 EBADF (Bad file descriptor)
...
```

Not sure if related. Please let me know if this seems related of if I should open another issue. In any case, I'm able to provide more info you deem necessary to debug this.

**Comment by BenBE** [comment]
@Nuc1eoN Can you try the work-around mentioned by @fasterit in https://github.com/htop-dev/htop/issues/534#issuecomment-780372678? Also: If that one doesn't help, could you try to bisect asmentioned by me earlier (with and without that workaround applied)?

But given the error message of the `fstat64` this looks like some other issue to me. Could you provide a (more) complete dump of the situation?

**Comment by cgzones** [comment]
@nuno-silva  could you give #649 a try?

**Comment by nuno-silva** [comment]
> @nuno-silva could you give #649 a try?

I just tried applying #649 on top of master (as of 8154125d4bf):
```
  htop 3.0.6-dev

  platform:                  linux
  os-release file:           /etc/os-release
  (Linux) proc directory:    /proc
  (Linux) openvz:            no 
  (Linux) vserver:           no 
  (Linux) ancient vserver:   no 
  (Linux) affinity:          yes
  (Linux) delay accounting:  yes
  (Linux) sensors:           yes
  (Linux) capabilities:      yes
  unicode:                   yes
  hwloc:                     no 
  debug:                     no 
  static:                    no 
```

and it seems to work. Process list appears populated. Thank you @cgzones :)
