### ISSUE TITLE
Provide a way to select which sensor to use for CPU temperature

### ISSUE THREAD

**Issue by hrw** [htop-dev/htop#538]
At the moment htop has hardcoded list of x86-64 cpu sensors. So it does not read them on my computers ;(

```
[hrw@jagular htop]$ sensors
acpitz-acpi-0
Adapter: ACPI interface
temp1:        +61.0°C  (crit = +95.0°C)
temp2:        +60.0°C  (crit = +95.0°C)
temp3:        +61.0°C  (crit = +95.0°C)
temp4:        +60.0°C  (crit = +95.0°C)
temp5:        +60.0°C  (crit = +95.0°C)
temp6:        +60.0°C  (crit = +95.0°C)
temp7:        +60.0°C  (crit = +95.0°C)
temp8:        +59.0°C  (crit = +95.0°C)
temp9:        +60.0°C  (crit = +95.0°C)
```

For now I added 'acpitz' to hardcoded list but that's not a good solution.

**Comment by BenBE** [comment]
Related to #529 …

**Comment by fasterit** [comment]
Just FTR acpitz = ACPI Thermal Zone

**Comment by hardhub** [comment]
Why is it closed?

It is not possible to choose lm_sensors value.

I need to choose motherboard sensor, because only that one is accurate.

**Comment by BenBE** [comment]
Because we're not going to implement sensor readout from sysfs directly and there's #200 will likely bring the flexibility needed to choose the sensor to use for the meters … apart from that: [read that fine manual](https://linux.die.net/man/5/sensors.conf) for libsensors if you need to re-assign things.
