### ISSUE TITLE
Feature request: Show "true" CPU usage.

### ISSUE THREAD

**Issue by pthfdr-42** [htop-dev/htop#545]
Add a option to show CPU usage in frequencies.
Basically, multiply the percentage and the current core frequency.
Nearly every current CPU have the ability to dynamically adjust the frequency, and on smartphones there are different cores on the same SoC, so the "CPU usage" is pointless without frequency.

**Comment by fasterit** [comment]
Processes are typically dynamically re-assigned between cores, esp in the big-little architectures you refer to. And cores change frequencies faster than you can watch screen updates. So that doesn't seem like a reasonable feature request to me.

You can add the CPU frequency to the meters and watch the show a bit (in case you have not discovered that option yet).

/DLange

**Comment by BenBE** [comment]
This doesn't make much sense for several reasons. The first reason is, as @fasterit mentioned, that CPU cores can change their frequency several times a second. Thus when we snapshot the utilization for display there's no good way we could return this to meaningful "timeslot" counts.

The second thing is that the calculation of `ticks * frequency` doesn't make much sense unit-wise. Even more sore given the above argument that things could just have switched speed right before we query things from the kernel.
