### ISSUE TITLE
CPU Temp Readout from /sys/class/thermal/thermal_zone

### ISSUE THREAD

**Issue by meskilla** [htop-dev/htop#610]
Odroid Xu4 is using /sys/class/thermal/thermal_zone and has no libsensors support (sensor-detect shows no findings).

htop fork from [wbenny](https://github.com/wbenny/htop/blob/master/linux/CPUTempMeter.c) does offer the code as CPUTempMeter.c

I also like wbenny's approach to display cpu temp and cpu frequency on the right side column as a meter. The only code that is missing is support for multiple governor policies: Odroid Xu4 octa-core has two frequency scopes and can use two governors. It would be nice to display them individually like:

```
[cpu policy #1] [governor] [frequency] [cpu temp 1]
[cpu policy #2] [governor] [frequency] [cpu temp 2]

```

**Comment by BenBE** [comment]
Thank you for suggesting this patch. In our implementation we intentionally tried to focus on libsensors instead of reading these things ourselves as otherwise we'd have to implement such fallbacks for all possible sensors; because some platform will just not provide something. That being said, I'm quite reluctant right now to include this, as it would open up the way to open the flood gates of various other similar features. When we implemented the temperature/CPU speed feature, we discussed this topic in the team and decided to stick to libsensors as source for these information as this heavily reduces the maintenance work going forward.

Regarding the patch itself: The patch targets htop 2.x and thus likely needs several code changes to work together with current htop 3.x releases. One such change is the use of the degree sign, which is a bit tricky in ncurses and has explicit handling in `CRT.c`. Also the code should follow the `STYLEGUIDE`.

**Comment by Lin-Admin** [comment]
IMHO the idea to allow showing temperatures behind each CPU was an inappropriate improvement for the worse...

Please explain which chip models do have a temperature sensor measuring each CPU???

The exynos 5422 in Odroid XU4 does have 5 sensors attached to various zones _not_ related to any precise CPU.

I have improved the code by wbenny to read out all thermal zones a device shows in  "/sys/devices/virtual/thermal/thermal_zoneX/temp" and to display the maximum value seen together with the zone it occurred. (One could as well display all 5 zones, but IMHO the maximum is more interesting.)

I also have improved the CPU frequency meter so that it does display the frequency of group4 on CPU's who show that additional value.
In case you are interested in that code, please let me know.

Regarding coding style: The code from wbenny is as good or bad as the original htop code. I did not try to compile it together with your new git because IMHO the make file approach is the ugliest hack ever seen...

IMHO you need cleaning up that mess before criticising other code ;)

Regarding usabilty of libsensors on various ARM platforms, I do have well founded doubts that it will be implemented in foreseeable future?

**Comment by BenBE** [comment]
Many thanks for your constructive feedback. Let's go through it, to make sure I understand your point correctly.

> IMHO the idea to allow showing temperatures behind each CPU was an inappropriate improvement for the worse...
> 

In what regard has this new feature worsened the user experience. Can you please elaborate and name concrete points that would improve it and how?

> Please explain which chip models do have a temperature sensor measuring each CPU???
> 

If finding that information in an automated way was feasible I'm sure the libsensors people would be more than happy about a pull-request solving that long-standing issue. From a user experience PoV it'd even make those pesky configuration files obsolte that nobody understood ever anyway. Glory will be all yours!

> The exynos 5422 in Odroid XU4 does have 5 sensors attached to various zones _not_ related to any precise CPU.
> 
> I have improved the code by wbenny to read out all thermal zones a device shows in "/sys/devices/virtual/thermal/thermal_zoneX/temp" and to display the maximum value seen together with the zone it occurred. (One could as well display all 5 zones, but IMHO the maximum is more interesting.)
> 
> I also have improved the CPU frequency meter so that it does display the frequency of group4 on CPU's who show that additional value.

The current implementation in htop allows for that just fine. Just properly configure your libsensors and it will work as expected.

> In case you are interested in that code, please let me know.
> 

That sure sounds interesting. How much of it is generic enough to work with chips besides the Exynos 5422 you mentioned above? Which htop version does your patch target?

> Regarding coding style: The code from wbenny is as good or bad as the original htop code. I did not try to compile it together with your new git because IMHO the make file approach is the ugliest hack ever seen...
> 

I'm curious. Could you please elaborate on this point?

I've worked both on the htop 2.x and htop 3.x code and while I'm not a huge fan of autotools myself it's at least a huge improvement over the old build system in htop 2.x.

> IMHO you need cleaning up that mess before criticising other code ;)
> 

Got a todo list for us to follow along?

> Regarding usabilty of libsensors on various ARM platforms, I do have well founded doubts that it will be implemented in foreseeable future?

I wonder about that. Given how many Linux distributions package libsensors and how many of those run on ARM it's practically already supported. What's usually missing is someone bothering to write up some configuration to assign names to those sensors. But well, YMMV.

**Comment by Lin-Admin** [comment]
> In what regard has this new feature worsened the user experience. Can you please elaborate and name concrete points that would improve it and how?

The user is mislead to believe that all 8 CPU's do have an attached temperature sensor.

> If finding that information in an automated way ...
The result does not depend on the search strategy. You won't find any and libsensors people obviously did not yet care for ARM (Rasperberry Pis and Odroid).

>The current implementation in htop allows for that just fine. Just properly configure your libsensors and it will work as expected.

The average user will not be prepared to tweak libsensors config.

> I wonder about that. Given how many Linux distributions package libsensors and how many of those run on ARM it's practically already supported..

Did you ever try to use libsensors on Rasperberry Pi or XU4???
Obviously or mileages do _significantly_ vary...

**Comment by fasterit** [comment]
There is a default interface for hardware-monitoring in the kernel and that is so libsensors can abstract hardware specifics away (with some configuration help usually). See https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface . It is counter-productive to implement each hardware platform that does its own in each tool that wants to show a temperature.
Samsung should do this once and not every systems management tool or desktop environment again and again.
/DLange

**Comment by Lin-Admin** [comment]
If ever dictator _fasterit_ would show same speed in fixing bugs as he rashly closed this item, the situation of htop would be much better...

That so called **default** interface to hardware called libsensors will most probably take years before temperatures in Exynos and other Arm SoCs like BananaPi, Raspberry Pi etc. will become supported.

If the hasty decision of _fasterit_ determines future action of htop, this useful program will not be usable on all these systems for much too long time.

IMHO this requires more discussion and a firm decision by the team. I therefore ask to reopen this issue and after sufficient discussions to take a formal decision of the team.

![etop-2 0 4_Screen](https://user-images.githubusercontent.com/72185880/117576819-9180bf80-b0e7-11eb-90a1-cb25cc7d75e1.png)

**Comment by BenBE** [comment]
Just so much: To stick with libsensors instead of implementing each and every home-brew sensor ourselves was and still is a team decision (looking through our docs on that: end of Feb 2021, but earlier discussions came to the same decision) …

**Comment by natoscott** [comment]
@Lin-Admin please consider your tone carefully and communicate more respectfully here in future.

I assure you @fasterit does not behave like a "dictator" on this project, nor is he "rash" or "hasty" - I've found him to be well-considered in all his posts, including in this issue.
