### ISSUE TITLE
htop seems to count tmpfs into Disk IO

### ISSUE THREAD

**Issue by toralf** [htop-dev/htop#675]
I do bind-mount tmpfs here to my Gentoo images via bubblewrap [1]. It seems that it IO is counted by htop too (but shouldn't IMO)

[1] https://github.com/toralf/tinderbox/blob/master/bin/bwrap.sh#L139

**Comment by BenBE** [comment]
Given there are numerous ways that fiels could be stored by a process to persist data, there's not much you can do except for special-casing each and every file system that could exist. While `tmpfs` is a quite obvious example of files just going into RAM there are examples like `afs` or `cifs` where it's not so obvious if you should call it still "Disk I/O" as targets of these file systems are networked systems. Even more complicated are cases like `fuse` where the high-level file system driver doesn't even give you a hint where things are going. They could be classical disk file systems like `ntfs3g` (NTFS), wrappers around other I/O like `encfs` or purely virtual ones like `ramfuse` and `nullfs`. Does storing to things like ntfs3g create I/O? Clearly yes. Actually double, because the kernel has to handle each block of data usually twice (once using FUSE and once for the underlaying block device. In this regard having `tmpfs` being counted as normal I/O is actually quite straight forward as it's just handling whatever data the kernel hands it and writes that into RAM. If you wanted to split that up by target device this would get complicated quite fast as this information is most likely not readily available on most systems.

**Comment by cgzones** [comment]
Is this about the DiskIO meter in the top header or the process coulmns, like *DISK WRITE*, *DISK READ*?

**Comment by toralf** [comment]
The former (meter in top header)

**Comment by cgzones** [comment]
Can you share the output of `/proc/diskstats` while the tmpfs filesystems are mounted?

**Comment by toralf** [comment]
`mr-fox ~ # cat /proc/diskstats
 259       0 nvme1n1 3863172 1200583 275328179 628920 53427106 1894831 3207270464 284059824 0 8403284 284688744 0 0 0 0 0 0
 259       2 nvme1n1p1 62 0 4904 14 0 0 0 0 0 28 14 0 0 0 0 0 0
 259       3 nvme1n1p2 291 0 16269 30 1 0 8 0 0 64 30 0 0 0 0 0 0
 259       4 nvme1n1p3 49362 27304 4589856 10611 563101 18148 52857320 30635580 0 92984 30646191 0 0 0 0 0 0
 259       5 nvme1n1p4 3813369 1173279 270713934 618259 52864004 1876683 3154413136 253424244 0 8322348 254042503 0 0 0 0 0 0
 259       1 nvme0n1 2720834 1212368 239041377 543689 53406658 1972120 3208079936 306432855 0 8225508 306976545 0 0 0 0 0 0
 259       6 nvme0n1p1 232 0 17184 34 0 0 0 0 0 60 34 0 0 0 0 0 0
 259       7 nvme0n1p2 9771 4244 126061 860 22734 77783 804136 7971 0 17796 8831 0 0 0 0 0 0
 259       8 nvme0n1p3 70584 33434 5596336 18845 563101 18148 52857320 29986268 0 102088 30005114 0 0 0 0 0 0
 259       9 nvme0n1p4 2640157 1174690 233298540 523942 52820823 1876189 3154418480 276438615 0 8119368 276962558 0 0 0 0 0 0
 254       0 dm-0 13872 0 116832 1500 100517 0 804136 324140 0 18176 325640 0 0 0 0 0 0
 254       1 dm-1 148 0 7040 40 1 0 8 0 0 28 40 0 0 0 0 0 0
`

but the majority of tmpfs write is probably made by https://github.com/toralf/tinderbox/blob/master/bin/bwrap.sh#L146 meaning within 1 of the 13 running bubblewrap'ed Gentoo Linux images

**Comment by cgzones** [comment]
From the `/proc/diskstats` output it seems not tmpfs IO usage is counted, but all IO is counted twice; once for the root disk `nvme1n1` and then for every physical partition (`nvme1n1p1`...).

This has been tried to resolve via https://github.com/htop-dev/htop/blob/ce27f8379d143d64ab6a7787fdf38cb864e18edd/linux/Platform.c#L556-L572

but probably there is need for a generic approach instead of hard-coding each disk naming scheme.

Maybe we can limit the counted disks by the ones listed in `/dev/disk/by-partuuid` (see https://wiki.archlinux.org/title/persistent_block_device_naming#by-partuuid)?

**Comment by BenBE** [comment]
Idea: Remove all trailing digits and see if you already got a match that is a prefix to the current string. If so, skip that entry:

- `loop0` -> `loop` -> No prefix yet, take it
- `nvme0n1` -> `nvme0n` -> Go on ahead and take it
- `nvme0n1p1` -> `nvme0n1p` -> `nvme0n1` is a prefix of that; we'll've seen this before in a sorted list, skip it
- `sda` -> Fine, take it
- `sda1` -> `sda` -> Already got that one, skip it
…

**Comment by toralf** [comment]
FWIW:

`mr-fox ~ # btrfs filesystem show
Label: none  uuid: 59ad41c2-dedb-4097-99b2-6f404280ede4
        Total devices 2 FS bytes used 22.31GiB
        devid    1 size 128.00GiB used 30.01GiB path /dev/nvme0n1p3
        devid    2 size 128.00GiB used 30.01GiB path /dev/nvme1n1p3

Label: none  uuid: 65c018be-85e2-4066-b0e1-a9fec4bd4e83
        Total devices 2 FS bytes used 5.65TiB
        devid    1 size 3.24TiB used 2.93TiB path /dev/nvme0n1p4
        devid    2 size 3.24TiB used 2.93TiB path /dev/nvme1n1p4
`
/ is a 128 GB fs, spawned over 2 partitions of 2 NVMe's as  a RAID1
/data is a 6.5 TB fs, spawned over 2 partitions of 2 NVMe's as a RAID 0.

**Comment by cgzones** [comment]
@toralf Could you please give #758 a try?
