### ISSUE TITLE
Time sorted lexically rather than numerically, causing 1h to sort between 5min and 15min

### ISSUE THREAD

**Issue by corneliusroemer** [htop-dev/htop#753]
When any process time adds up to more than one hour and the time is displayed as `1h:xx` and I sort downwards by time, counter to my expection the largest time does not appear at the top but below some processes that are running only 10s of minutes.

This is a bug and could be caused by lexical rather than numeric sorting.

I will provide a screenshot as soon as my computer has been running for long enough (just restarted so not showing right now).

## System info
Installed via homebrew: /usr/local/Cellar/htop/3.0.5/bin/htop
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
MacOS: 11.5.2 (20G95)

**Comment by BenBE** [comment]
Do you have the tree view active? If so, the sorting is grouped by siblings of the same parent.
With the tree view disabled it shows times sorted numerically without grouping by their parent.

List without tree view:
![image](https://user-images.githubusercontent.com/111196/130328723-0f67f7f1-6a33-4fc6-9095-27ccfa126165.png)

List with tree view:
![image](https://user-images.githubusercontent.com/111196/130328732-433137c6-77fe-4496-9dd7-33864c6621ae.png)

This grouped-sorting-by-parent behavior is intentional.

**Comment by corneliusroemer** [comment]
You may be right, I'll close till I can check. thanks!
