### ISSUE TITLE
Segfault on exit due to double-free

### ISSUE THREAD

**Issue by Keating950** [htop-dev/htop#864]
I encountered a segfault on closing `htop` today, and after examining the core dump, I suspect it's due to a double-free in the `String_freeArray` function. I've attached the coredump here: [htop.dump.gz](https://github.com/htop-dev/htop/files/7460548/htop.dump.gz)

**Version**: 3.1.1
**OS**: Arch Linux
**Arch package version**: 3.1.1-1

**Comment by BenBE** [comment]
Let me quote the bug report message from htop:

> FATAL PROGRAM ERROR DETECTED                                                                                                                                                                 
> ============================
> Please check at https://htop.dev/issues whether this issue has already been reported.
> If no similar issue has been reported before, please create a new issue with the following > information:
>   - Your htop version: '3.1.1-1'
>   - Your OS and kernel version (uname -a)
>   - Your distribution and release (lsb_release -a)
>   - **Likely steps to reproduce (How did it happen?)**
>   - **Backtrace of the issue (see below)**
> 
> Error information:
> ------------------
> A **signal 42** (Manual-neglecting User) was received.
> 
> Setting information:
> --------------------
> …
> 
> Backtrace information:
> ----------------------
> …
> 
> **To make the above information more practical to work with, please also provide a disassembly of your htop binary**. This can usually be done by running the following command:
> 
>     objdump -d -S -w `which htop` > ~/htop.objdump
> 
> Please include the generated file in your report.
> Running this program with debug symbols or inside a debugger may provide further insights.
> 
> Thank you for helping to improve htop!

Just providing the raw coredump file doesn't quite help to debug the issue as that file depends on the actual `htop` binary from your system.

Leaving this aside: There was an off-by-one issue caused by a recent change. Please check again using the main development branch or apply https://github.com/htop-dev/htop/commit/604744f68d5c0375987eb9b60298f2affd1d8f38.
