### ISSUE TITLE
Threads info not available on Macos11.4 with htop3.1.2 

### ISSUE THREAD

**Issue by ruleil** [htop-dev/htop#886]
Threads info not available on Macos11.4 with htop3.1.2：
![image](https://user-images.githubusercontent.com/35195892/144796430-280085da-b6a9-4211-8679-53912c3a74fe.png)

What should I do next? Or what information should I collect to make it works?

**Comment by BenBE** [comment]
Cf. https://github.com/htop-dev/htop/issues/542

**Comment by ruleil** [comment]
@BenBE  Thanks for your information. I'm developing Macos App recently, could you give me some insight about why htop not able to show threads information on Macos? What should I do if I want to contribute to get htop works on Macos?

**Comment by BenBE** [comment]
> I'm developing Macos App recently, could you give me some insight about why htop not able to show threads information on Macos? What should I do if I want to contribute to get htop works on Macos?

There seems to be and old PR to implement these information for MacOS at https://github.com/hishamhm/htop/pull/848. To integrate this we'd either need confirmation from @robaho to re-use his PR or re-implement the changes outlined in that PR from scratch. Please note that the code base since 2.0.2 has changed significantly, thus straight forward porting of those changes is unlikely to work out-of-the-box.

Furthermore it'd be great if we found a way to avoid the sudo requirement mentioned in the old PR, but since I take extra care to properly keep my distance from any half-eaten fruits I can't help you there too much in this regard.

There's also https://github.com/htop-dev/htop/pull/546 by @cgzones which still has some details to work on and probably also needs some rebasing by now. Maybe cleaning up on that front might be worth a shot too.

**Comment by robaho** [comment]
If you need htop with threads I would use the https://github.com/hishamhm/htop/pull/848 and be done with it.

I am not sure why this project even exists over the other - nor why the PR wasn't applied when this project was created.

**Comment by ruleil** [comment]
@BenBE @robaho  Thanks for your information. I will do some test based on PR  [hishamhm/htop#848](https://github.com/hishamhm/htop/pull/848). At the beginning, I think this PR is already merge into master branch.

**Comment by BenBE** [comment]
> I am not sure why this project even exists over the other - nor why the PR wasn't applied when this project was created.

When the PR was created hisham (the original author of htop) has been inactive with further development of htop for quite some time. In August 2020 a group of developers from the community of people using htop took over development and they created this repository because hisham couldn't be reached. And when hisham finally got in contact with the people behind this project it was agreed to archive his github repository to indicate to people where the new place of development is: This repository.

On the other side this also means, that PRs created for the old repository aren't directly applicable here because we'd like the original author's approval for merging their work with a project that has changed maintainership since - and which also got some minor updates with its licensing that people should be aware of (some simplifications/clarifications over the old repository).

Thus, @robaho, if you agree that we can use your code as a base to work on to integrate the necessary changes into an official htop build, this would be nice and help a lot going forward with it.

> If you need htop with threads I would use the [hishamhm/htop#848](https://github.com/hishamhm/htop/pull/848) and be done with it.

The branch over there may work as intended, but the overall version there is **no longer maintained**. Thus plainly using that PR without proper porting to the current main development branch is **not recommended for production** use.

As part of the other issues and PRs I linked from this repository work should be concentrated to get either that old PR ported+working (requires consent from @robaho to use those code changes) or complete the work on the PR by @cgzones I linked.

> @BenBE @robaho Thanks for your information. I will do some test based on PR [hishamhm/htop#848](https://github.com/hishamhm/htop/pull/848).

@ruleil: That PR is likely not directly forward-portable to current development head due to massive cleanups of the code that happened since htop 2.2.0 code base that that PR is based upon. In particular we introduced several changes to how we organize memory management to reduce the possibilities of errors in the code. This will have to be updated in the PR, among other things.
