### ISSUE TITLE
docs: ncurses dependency ("how to install ncurses")

### ISSUE THREAD

**Issue by vielmetti** [htop-dev/htop#89]
The docs currently say that htop depends on ncurses, but they leave open the question
of how precisely to install ncurses on the many systems that package it in so many ways.

In the interests of reducing the frequency of ncurses-related issues - like #85 #36 #82 -
this issue will be resolved with a PR for a new file in the docs `README-ncurses.md` with  
install instructions.  

Ideally, this will be fodder for some kind of CI infrastructure that automatically tests those
directives when it builds and tests across a variety of operating systems.

**Comment by eli-schwartz** [comment]
If #80 goes through, you could add a meson wrap for ncurses which tells meson to download and build ncurses if it cannot be found. This would also make it trivial to build a static binary that doesn't link to the system ncurses.

**Comment by fasterit** [comment]
Knowing how to install some header files for your distro of choice is about as basic as it gets when you start developing. So there is an abundance of documentation on this and I'd much prefer we do not add another basic walk-through of typically two commands to this repo for this information to then bitrot as nobody will care to keep it up to date.
Also there is 100+ distros and I don't want to have dozens of PRs to add yet another obscure distro to this file.
That said, the README is wrong/unclear in two places, so that can be improved. But no generic "how to start developing in C tutorials" in the repro please.
