### ISSUE TITLE
Suggestion: Hide userland threads by default

### ISSUE THREAD

**Issue by C0rn3j** [htop-dev/htop#99]
People casually using htop usually have no idea what userland threads are for.
People who actually need to see them can easily enable them via SHIFT+H.

With them currently enabled by default, it is very inconvenient to go through the list and see what is running, taking up RAM, CPU usage and whatnot, therefore I think it'd be more user-friendly to not show them by default.

These values are 1 by default, change to 0 upon pressing SHIFT+H, I couldn't figure out what exactly to change in code otherwise I'd send a PR directly:
```
hide_userland_threads
hide_threads
```

Current situation:
![image](https://user-images.githubusercontent.com/1641362/92379129-384f2f00-f107-11ea-8640-5e2074c068de.png)

Userland threads off (SHIFT+H):
![image](https://user-images.githubusercontent.com/1641362/92379174-4ef58600-f107-11ea-92b4-0dd6c135ce9a.png)

**Comment by fasterit** [comment]
That doesn't make sense. Hiding what you see can be useful and is discoverable. But having to find out what could be there is much harder.
So hiding these by default violates the discoverability principle of good UI (user interfaces).

You - obviously - can change your personal default as per your preference and it will save automatically to your .htoprc.

**Comment by C0rn3j** [comment]
People new to htop do not even realize that those are threads under an existing process and thus for their reason useless duplicates.

Or that they can hide them.

I see people very often posting htop screenshots with the threads enabled when asking for help, and they're happy to find out they can be disabled and that it makes htop actually usable to view a casual overview.

>So hiding these by default violates the discoverability principle of good UI

Htop has a huge amount of features hidden by default already because it would make no sense to show them all as the window would be cluttered, which is exactly the case here, userland threads are clutter to most people.

**Comment by fasterit** [comment]
htop is a tool for people who know about systems management, processes and threads. If a user does not know what a process is and what a thread is, htop is not really that useful.

Your argument what is "clutter to most people" is made up to support your personal preference. That is bogus.
Go run some systems in a big Java shop and you want to see the threads.

Just change your setup how you like it, no need to force that on everybody else. The default was fine for a decade and I see no reason to change it.
It is not that much work to press F2 and adjust to what you like best.

**Comment by C0rn3j** [comment]
> Go run some systems in a big Java shop and you want to see the threads.
Great, so enable them in the config management, this is a non-issue for a systems admin.

>Just change your setup how you like it, no need to force that on everybody else.

I change my own, and the systems I manage have a managed config.

>htop is a tool for people who know about systems management, processes and threads

No, it is definitely by use in people who are not system administrators, you are completely ignoring desktop usage.

**Comment by fasterit** [comment]
> > htop is a tool for people who know about systems management, processes and threads
> 
> No, it is definitely by use in people who are not system administrators, you are completely ignoring desktop usage.

"Know about systems management, processes and threads" includes desktop usage.

**Comment by BenBE** [comment]
While I personally have userland threads visible I strongly agree with @C0rn3j that for the casual user they are probably of only little use and much noise.

@C0rn3j Cf. Settings.c -> function `Settings_new` -> `this->hideThreads = true;` …
Looking forward to that PR.

**Comment by SharkWipf** [comment]
More-than-casual-user here, managing a few 100 servers, even for me, userland threads are nothing but noise and always the first thing I disable so I can actually see what's going on.  
I'd agree with @C0rn3j that it's more likely userland threads are undesirable noise than actually insightful to most users, and that the users who'd want to see them know how to enable them.

**Comment by hishamhm** [comment]
Hi @C0rn3j, I thought I'd drop by and give a bit of historical background as to what was my motivation for showing threads by default.

> People casually using htop usually have no idea what userland threads are for.

Yes! I fully sympathize with this sentiment. And the choice for enabling threads **and painting them green** was deliberate.

You have no idea how many times I was asked "hey, why are some processes green?" over these 15+ years — and no, it wasn't annoying: each of these times it was an opportunity to teach someone about threads!

![image](https://user-images.githubusercontent.com/245621/102625820-cc785b80-4124-11eb-984c-3187652a7875.png)
([credit: xkcd](https://xkcd.com/1053/))

htop was designed to provide a view to what's going on in the system. If a process is spawing threads like crazy, or if all your cores are overwhelmed because multiple threads of a process are doing work, I think it's fair to show it to the user, even if they don't know a thing about threads — or I would say, *especially* if they don't know a thing about threads, otherwise these things would be happening and they wouldn't even know where to look.

> Htop can also show Disk IO, which can be arguably very useful, but is hidden by default.

One of my last projects when I was still active in htop development was to add _tabs_ to the interface, so that the user would have a more discoverable path for navigating through these additional columns:

![image](https://user-images.githubusercontent.com/245621/102626509-a7d0b380-4125-11eb-9bd3-6c6f04071eb0.png)

This code is in the `next` branch of the old repo https://github.com/hishamhm/htop/ — I think the code for tabs is actually finished (though not super tested); it's pretty nice, you can click on them or cycle with the Tab key, but the Perf Counters support which I was working on, never really got stable to a point of my liking, and that's when I got busy with other things and drifted away from development — turns out I enjoy writing interface code a lot more than the systems monitoring part!

Anyway, I think that also illustrates the pattern that went into the design: I implemented the entire tabs feature **because I wanted to make IO and Perf Counters more discoverable**. I wanted to put that information in front of users faces, _especially for users who don't know about these things_! I considered the fact the I had implemented the entire functionality of iotop inside htop but people didn't know about it (and even I didn't use it because it wasn't convenient) to be a personal failure, and a practical learning experience: adding systems functionality is useless if the UI design doesn't get it to users' hands.

I never wanted to implement a tool for "super advanced Linux power users who know what they doing", otherwise I would have never spent a full line at the bottom showing F-keys, and I would have spent my time implementing Vim bindings (ugh :wink: ) instead of mouse support. I've always made a point that _every setting can be settable via the Setup screen_, which you can access via F2-Setup (shown at the bottom line!) and which you can control with the keyboard or mouse, no "edit this config file to use this advanced feature for the initiated only" or even "read the man page" (in fact it only has a man page because Debian developers contributed it!).

I wanted to make a tool that has the power but doesn't hide it from users, and instead invites users into becoming more powerful. A tool that reaches out its hand and guides them along the way, helping users to educate themselves about what's happening on the internals of their system, and in this way have more control of it. This is how you hand power to users, not by erecting barriers of initiation or by giving them the bare minimum they need. I reject this dicothomy between "complicated tools for power users" and "stripped-down tools for mere mortals", the latter being a design paradigm made popular by certain companies and unfortunately copied by so many OSS GUI projects, without realizing what the goals of that paradigm really were, but that's another rant.

And that's why threads are enabled by default, and colored in green!

(PS: and to put the point to the proof, I must say that the tabs feature was a much bigger code change than Perf Counters themselves; it included some quite big internal refactors (there's no "toolkit", everything is drawn "by hand" by htop) with unfortunately might make it difficult to ressurect that code (or not! who knows?), and of course tabs are user-definable and user-editable!)

**Comment by C0rn3j** [comment]
I had no idea anything like that was in development.

The tab feature looks extremely useful and makes this entire argument moot, as you could have different default tabs for showing a lot, little, and specific things like IO, namespaces and so on, like your screenshot shows.

Thanks a lot for the explanation and history tidbits!

I am closing this issue as both you and current maintainers are against it, and the tabs feature would be a much nicer solution to it anyways.
